---
  - name: Check if docker swarm is enabled
    shell: docker info
    changed_when: false
    register: docker_info

  - name: Store the worker token
    shell: docker swarm join-token -q worker
    changed_when: false
    register: docker_worker_token
    delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
    when: "docker_info.stdout.find('Swarm: active') == -1"

  - name: Adds worker servers on cluster
    shell: docker swarm join --token "{{ docker_worker_token.stdout }}" {{ docker_swarm_manager_ip }}:{{ docker_swarm_manager_port }}
    changed_when: false
    when: "docker_info.stdout.find('Swarm: active') == -1
           and docker_info.stdout.find('Swarm: pending') == -1"
    tags: add_workers

  - name: Turn on UFW
    community.general.ufw:
      state: enabled
      policy: allow

  - name: Set logging
    community.general.ufw:
      logging: 'on'

  - name: Open Docker daemon and Swarm ports on Swarm workers (TCP ports)
    community.general.ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    with_items:
      - 22   # Allow SSH connections.
      - 80   # Allow HTTP connections.
      - 2376 # For secure Docker client communication.
             # This port is required for Docker Machine to work.
             # Docker Machine is used to orchestrate Docker hosts.
      - 7946 # TCP/UDP for nodes' communication (container network discovery).

  - name: Open Swarm ports on Swarm workers (UDP ports)
    community.general.ufw:
      rule: allow
      port: "{{ item }}"
      proto: udp
    with_items:
      - 7946 # TCP/UDP for nodes' communication (container network discovery).
      - 4789 # For overlay network traffic (container ingress networking).

  - name: Set to deny incoming requests by default
    community.general.ufw:
      default: deny
...
