---
  - name: Check if docker swarm is enabled
    shell: docker info
    changed_when: false
    register: docker_info

  - name: Store the worker token
    shell: docker swarm join-token -q worker
    changed_when: false
    register: docker_worker_token
    delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
    when: "docker_info.stdout.find('Swarm: active') == -1"

  - name: Adds worker servers on cluster
    shell: docker swarm join --token "{{ docker_swarm_token.stdout }}" {{
    docker_swarm_manager_ip }}:{{ docker_swarm_manager_port }}
    changed_when: false
    when: "docker_info.stdout.find('Swarm: active') == -1
           and docker_info.stdout.find('Swarm: pending') == -1"
...
